spring:
  application:
    name: spring-cloud-eureka
#  profiles: peer1
server:
  port: 9999
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/